### ISSUE TITLE
Basecamp API implementation

### ISSUE THREAD

**Issue by aboza** [mark-hahn/basecamp#1]
I know this post is for issues, but I dont know where to post this questions XD, there are some example about the implementation of basecamp api for node.js?, Im trying to user you NP but i cant get it work....

**Comment by mark-hahn** [comment]
Sorry I missed your question.  I had github going to spam for a while.

The only code that used this is proprietary and I can't share it.  I would be happy to answer specific questions.

**Comment by pranab1981** [comment]
I found this "very useful" package, and I am trying my hand at it today. Can you provide some sample code on using the authNewCallback method? I am a bit confused on where/how to use this callback method. I was able to create a client, and generate the authNewUrl using the getAuthNewUrl function.

also, if you could provide a small sample for fetching the data for, say for instance, one message or one task from basecamp into the application: it would be very helpful and provide as a guide for all other available functions. thx, and looking forward

**Comment by mark-hahn** [comment]
Unfortunately I developed that for a project I was on and I haven't touched
it in a couple of years, since right after I published it.  I can't show
you any code from that project and I don't remember anything about basecamp.

I'm sorry for not supporting it.  I hope you still find it useful.  If
nothing else it should help to understand basecamp.
